# .github/workflows/frontend.yml
name: Frontend CI/CD

on:
  push:
    paths:
      - "frontend/**"
  pull_request:
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run linting
        run: |
          cd frontend
          npm run lint

      - name: Build project
        run: |
          cd frontend
          npm run build
